# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20171113_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='prize',
            field=models.CharField(default=20, max_length=200),
            preserve_default=False,
        ),
    ]
