# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
